apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jing-gitlab
  namespace: jing-gitlab
spec:
  ingressClassName: 'nginx'
  rules:
  - host: code.jingli.com
    http:
      paths:
      - backend:
          service:
            name: jing-gitlab
            port: 
              number: 80 
        path: /
        pathType: Prefix
  - host: jing-gitlab.jingli.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jing-gitlab
            port:
              number: 80
